src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\BlogPost;
use App\Entity\User;
use App\Form\Type\BlogPostType;
use App\Utils\Slugifier;
use Doctrine\DBAL\Types\StringType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{

    /**
     * @Route("post/new", name="new_post")
     */
    public function new(Request $request): Response
    {
        // creates a task object and initializes some data for this example
        $post = new BlogPost();
        $dateTime = new \DateTime();
        $dateTime->setTimezone(new \DateTimeZone('Europe/Berlin'));
        $post->setUpdated($dateTime);

        $form = $this->createForm(BlogPostType::class, $post);
        $email = $this->getUser()->getUsername();
        $author = $this->getDoctrine()->getManager()->getRepository(User::class)->findOneBy(['email' => $email]);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $blogPost = new BlogPost();
            $blogPost->setTitle($data->getTitle());
            $blogPost->setBody($data->getBody());
            $blogPost->setAuthor($author);
            $blogPost->setSlug(Slugifier::slugify($data->getTitle()));
            $blogPost->setUpdated($dateTime);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($blogPost);
            $entityManager->flush();

            return $this->redirectToRoute('homepage');
        }

        return $this->render(
            'blog/new.html.twig',
            [
                'blogPostForm' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("post/edit/{slug}", name="edit_post", methods={"GET", "POST"})
     */
    public function edit(Request $request, BlogPost $post)
    {
        $form = $this->createForm(BlogPostType::class, $post);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $post->setTitle($data->getTitle());
            $post->setBody($data->getBody());

            $dateTime = new \DateTime();
            $dateTime->setTimezone(new \DateTimeZone('Europe/Berlin'));
            $post->setUpdated($dateTime);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('homepage');
        }

        return $this->render(
            'blog/edit.html.twig',
            [
                'blogPostForm' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("post/{slug}", name="blog_post", methods={"GET", "POST"})
     */
    public function show(BlogPost $blogPost): Response
    {
        return $this->render(
            'blog/show.html.twig',
            [
                'post' => $blogPost,
            ]
        );
    }

    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {
        $blogList = $this->getDoctrine()->getManager()->getRepository(BlogPost::class)->findAllOrderedByTime();
        return $this->render(
            'blog/index.html.twig',
            [
                'controller_name' => 'BlogController',
                'blogPosts' => $blogList,
            ]
        );
    }

}

templates/blog/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <style>
        textarea#blog_post_body {
            margin: 10px 10px 0 10px;
            width: 365px;
            height: 175px;
        }

        input#blog_post_title {
            margin: 10px;
        }

        button.btn.btn-primary {
            margin: 10px;
        }

    </style>

    <h1>Edit post</h1>
    {{ form_start(blogPostForm) }}
    {{ form_widget(blogPostForm) }}
    <button type="submit" class="btn btn-primary">Save!</button>
    {{ form_end(blogPostForm) }}
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome to the blog!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }
    .styled-table thead tr {
        background-color: #009879;
        color: #ffffff;
        text-align: left;
    }
    .styled-table th,
    .styled-table td {
        padding: 12px 15px;
    }
    .styled-table tbody tr {
        border-bottom: 1px solid #dddddd;
    }

    .styled-table tbody tr:nth-of-type(even) {
        background-color: #f3f3f3;
    }

    .styled-table tbody tr:last-of-type {
        border-bottom: 2px solid #009879;
    }
    .styled-table tbody tr.active-row {
        font-weight: bold;
        color: #009879;
    }
</style>

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}
    {% if app.user == false %}
        <div class="mb-3">
            <a href="{{ path('app_login') }}"
               class="button is-primary">
                Login
            </a>
        </div>
    {% endif %}

<div class="example-wrapper">
    <h1>Welcome to the blog!</h1>

    <a href="{{ path('new_post') }}" class="button is-primary">
        Create a new Entry
    </a>

    <table class="styled-table">
    <tr>
        <th>Post </th>
        <th>Author</th>
        <th>Updated</th>
        {% if app.user and "ROLE_ADMIN" in app.user.roles %}<th>Edit</th>{% endif %}
    </tr>
    {% for blogPost in blogPosts %}
        <tr>
            <div>
                <div>
                    <td>
                    <a href="{{ path('blog_post', {'slug': blogPost.slug}) }}"
                       class="button is-primary">
                        {{ blogPost.title }}
                    </a>
                </div>
                <div>
                    {{ blogPost.body | slice(0,40) }}...
                </div>
            </div>
            </td>
            <td>{{ blogPost.author.email }}</td>
            <td>{{ blogPost.updated.format('Y-m-d\ H:i:s') }}</td>
            {% if app.user and "ROLE_ADMIN" in app.user.roles %} <td>
                <a href="{{ path('edit_post', {'slug': blogPost.slug}) }}" class="button is-primary">
                    Edit
                </a>
                </td>
            {% endif %}

        </tr>
    {% endfor %}

    </table>

</div>
{% endblock %}

templates/blog/new.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <style>
        textarea#blog_post_body {
            margin: 10px 10px 0 10px;
            width: 365px;
            height: 175px;
        }

        input#blog_post_title {
            margin: 10px;
        }

        button.btn.btn-primary {
            margin: 10px;
        }

    </style>
    <h1>Create a new post! ?</h1>
    {{ form_start(blogPostForm) }}
    {{ form_widget(blogPostForm) }}
    <button type="submit" class="btn btn-primary">Create!</button>
    {{ form_end(blogPostForm) }}
{% endblock %}

templates/blog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ post.title }}{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }

    </style>

    <a href="{{ path('homepage') }}"
       class="button is-primary">
        To Blogs!
    </a>

    <div class="example-wrapper">
        <h1>✅ Blog Entry by user {{ post.author.email }} </h1>
        <h3> {{ post.title }} </h3>
        <div>{{ post.body }}</div>

    </div>
{% endblock %}